services:
  backend:
    build: .
    container_name: ebuy-backend
    ports:
      - "3000:3000"
    volumes:
      - ./dev.db:/app/dev.db
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=super-secret-key-change-this

  frontend:
    build: ../frontend
    container_name: ebuy-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  studio:
    build: .
    container_name: ebuy-studio
    ports:
      - "5555:5555"
    volumes:
      - ./dev.db:/app/dev.db
    command: npx prisma studio --hostname 0.0.0.0 --port 5555 --browser none
